# Generated by Django 4.2.1 on 2023-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_date', models.DateField()),
                ('directors', models.CharField(max_length=300)),
                ('writers', models.CharField(max_length=300)),
                ('genres', models.CharField(max_length=100)),
                ('storyline', models.TextField(blank=True, null=True)),
                ('trailer_url', models.URLField()),
                ('cover', models.ImageField(upload_to='images/covers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
